# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Florian Schuttkowski"
description: >- # this means to ignore newlines until "baseurl:"
  Wie alles was ich tue, widme ich diese Website den drei Frauen,
  die mein Leben tagtäglich bereichern: meinen Kindern und meiner Partnerin. Danke für eure Liebe und die
  Erfahrungen, die ich an eurer Seite machen darf. 
author: Florian Schuttkowski 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://florianschuttkowski.com" # the base hostname & protocol for your site, e.g. http://example.com

include: 
  - _pages

permalink: /:year/:title

theme: minima
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
      
header_pages:
  - _pages/cv.md
  - _pages/my-work.md
  - _pages/kontakt.md
  - _pages/downloads.md
  - _pages/gallery.md

minima:
  skin: latex
  date_format: "%d.%m.%Y"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
