title: "Florian Schuttkowski"
url: "https://florianschuttkowski.com"
lang: de-DE
include:
  - _pages

header_pages:
  - _pages/cv.md

footer_pages:
  - _pages/impressum.md
  - _pages/datenschutz.md

plugins:
  - jekyll-feed

# This is needed to disable rouge as the default highlighter in jekyll.
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true